name: CI
on:
  push:
    branches:
      - master # need to filter here so we only deploy when there is a push to master
  # no filters on pull requests, so intentionally left blank
  pull_request:
  workflow_dispatch:

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python libraries
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install ghp-import
        pip install -U git+https://github.com/tensorflow/docs
    - name: Notebook formatting and linting
      run: |
        python3 -m tensorflow_docs.tools.nbfmt nbs
        python3 -m tensorflow_docs.tools.nblint --fix nbs
    - name: Building HTML site
      run: |
        jupyter-book build .

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        publish_branch: gh-pages
