name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python libraries
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install ghp-import
        jupyter-book build .
        ghp-import -n -p -f _build/html
        
